# Generated by Django 2.0.2 on 2018-05-31 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelfork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_book.Novel'),
        ),
    ]
