# Generated by Django 2.0.1 on 2018-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spider', '0003_auto_20180129_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('ip', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('survival_time', models.CharField(max_length=255)),
                ('verification_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UrlResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('href', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, max_length=255, null=True)),
                ('spider_times', models.IntegerField(default=0)),
                ('error_times', models.IntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
