# Generated by Django 2.0.2 on 2018-05-31 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douban_id', models.CharField(blank=True, max_length=190, null=True, unique=True)),
                ('json_data', models.TextField()),
                ('show_times', models.IntegerField(default=0)),
                ('select_times', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoubanMovieSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('douban_id', models.CharField(blank=True, max_length=190, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_x', models.IntegerField(default=0)),
                ('cover_y', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=False)),
                ('rate', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('douban_tag', models.CharField(blank=True, max_length=190, null=True)),
                ('douban_type', models.CharField(blank=True, max_length=190, null=True)),
                ('level', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('download_link', models.TextField(blank=True)),
                ('download_uuid', models.CharField(default=None, max_length=100, null=True, unique=True)),
                ('show_times', models.IntegerField(default=0)),
                ('like_times', models.IntegerField(default=0)),
                ('dislike_times', models.IntegerField(default=0)),
                ('report_times', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieSimpleMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fork', models.NullBooleanField(default=None)),
                ('is_watched', models.NullBooleanField(default=None)),
                ('is_like', models.NullBooleanField(default=None)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('movie_simple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_movie.DoubanMovieSimple')),
            ],
        ),
    ]
